version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carepilot_web
    ports:
      - "8000:8000"
    env_file:
      - .env.${ENV:-development}
    volumes:
      - .:/app
    depends_on:
      - redis
    command: >
      bash -c "
        if [ \"$ENV\" = \"production\" ]; then
          alembic upgrade head;
        fi &&
        uvicorn dashboard.main:app --host 0.0.0.0 --port 8000 --reload
      "

  redis:
    image: redis:7
    container_name: carepilot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - development

volumes:
  redis_data:
